[tool.poetry]
name = "abi2csv"
version = "0.1.0"
description = ""
authors = ["Jérémie Roquet <jroquet@arkanosis.net>"]

[tool.poetry.dependencies]
python = "^3.8"
biopython = "^1.76"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
